### ISSUE TITLE
Feature Request: Transition Speed Adjustment

### ISSUE THREAD

**Issue by Majumafoo** [kizza/magic-home-party-card#1]
I am unable to change the transitions speed when using this implementation.
Attempting to adjust the transition speed  of the device throws an error, which presumably references stock effects:
`Failed to call service number/set_value. Speed can only be adjusted when an effect is active`

**Comment by kizza** [comment]
I've just been experiencing that myself actually (I thought you were able to adjust the effect speed individually on the light but yes, it seems you need to perhaps set it when the effect is started).  I'll have a play with this 👌

**Comment by kizza** [comment]
Well, thank you - that's so much better.  I've [cut a new release ](https://github.com/kizza/magic-home-party-card/releases/tag/v0.1.3) which I expect will propagate through HACS shortly (I actually didn't realise this repo had been approved via hacs, updated the readme also to reflect that).
